### ISSUE TITLE
Create card functionality

### ISSUE THREAD

**Issue by jcf0419** [Ho-Wan/vscode-trello-viewer#1]
I'd love to see add/edit card functionality.

**Comment by Ho-Wan** [comment]
Creating a card with a user specified title and in a particular list is a good feature to have, and possibly editing the title.

Editing description or content of card may not be too user friendly given the VS code interface, so that should be a low priority unless someone can come up with a good UI for it.

**Comment by jcf0419** [comment]
I've used another extension for work that does something similar in vscode with Jira. 
Basically it was something like:
ctrl+shift+p create item
Prompt: Enter item title
Prompt: Enter Short Description
Create or Add additional Optoins
If create - item was created with default fields
If Additional Options more prompts given.

**Comment by Ho-Wan** [comment]
Add card functionality implemented in v0.3.0
